###########
# site.title, site.url, site.author.name

title:   'Cornwall Ruby'
author:
  name:  'Cornwall Ruby Users Group'

## note:
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path:
url:  'https://cornwallruby.co.uk'
slackurl: https://join.slack.com/t/cornwallruby/shared_invite/enQtMjgwMTUyOTM0NzA1LWE3ZjBkYzRlMTE0YTcwZmJmZDI1MGUxODBkZDQ2NTY2MWQwYjYxOTg0NzE5ZWM0Y2MyNTJiNTI4ZTRmMDc0OWI
description: Cornwall Ruby is a group of hobbyists and professionals who use, and presumably like, the programming language Ruby. This user group is a way to meet other people in the industry locally with Ruby experience and to learn from each other.

########
# more settings
markdown: kramdown

sass:
  sass_dir: css
  style: compressed

permalink: /:title.html

exclude:
- README.md

lsi: false

plugins:
  - jekyll-sitemap
